# Generated by Django 4.2.25 on 2025-10-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='megavideo',
            name='video_source',
            field=models.CharField(choices=[('mega', 'MEGA'), ('pcloud', 'pCloud'), ('gdrive', 'Google Drive')], default='mega', help_text='Video hosting platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='megavideo',
            name='mega_file_link',
            field=models.URLField(help_text='Video link (MEGA/pCloud/Google Drive)', max_length=500),
        ),
    ]
